### ISSUE TITLE
Add install/build instructions

### ISSUE THREAD

**Issue by guiweber** [Shadlock0133/music-vibes#2]
I downloaded the source code but when I run `rustc main.rs` I get a bunch of errors. Seems like some dependencies may need to be installed first? It would be good to add install/build instructions!

**Comment by Shadlock0133** [comment]
Instead of using just `rustc`, practically all Rust project use `cargo` as package manager for building them. So to build you run `cargo build` (or `cargo build --release` for optimized build), which creates executable in `target/{debug, release}/program{.exe}`; or you can install with `cargo install --path .`.

Thanks for suggestion, I will add instructions in the readme.
